---
title: "Question 1 -Ann"
output: html_document
date: "2023-11-03"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
#setwd("~/Desktop/random/Krypton/SubTypeSalary")
salary_data <- read_excel("../salary_data_states.xlsx")

selected_groups <- c('data analyst', 'business analyst', 'data scientist')
useful_data <- salary_data %>%
  filter (JOB_TITLE_SUBGROUP %in% selected_groups)
```

```{r}
# Do specific sub-types of data-related jobs have higher or lower salaries than others? 
useful_data %>%
  group_by(JOB_TITLE_SUBGROUP) %>%
  summarize(AvgSalary = mean(PAID_WAGE_PER_YEAR)) %>%
  arrange(AvgSalary)
  
ggplot(data = useful_data, aes(x = JOB_TITLE_SUBGROUP, y = mean(PAID_WAGE_PER_YEAR), fill = JOB_TITLE_SUBGROUP)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Salaries of Job Subgroups",
       x = "Sub Group",
       y = "Average Salary")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# Which companies have the highest salaries for those sub-types? 
useful_data %>%
  group_by(JOB_TITLE_SUBGROUP, EMPLOYER_NAME) %>%
  summarize(AvgSalary = mean(PAID_WAGE_PER_YEAR)) %>%
  arrange(JOB_TITLE_SUBGROUP, desc(AvgSalary)) %>%
  top_n(1)
  
ggplot(summary_data, aes(x = EMPLOYER_NAME, y = AvgSalary, fill = JOB_TITLE_SUBGROUP)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Companies with the Highest Salaries for Job Subgroups",
       x = "Employer Name",
       y = "Average Salary") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
# Changes with location of the job? 
useful_data %>%
  group_by(WORK_STATE) %>%
  summarize(AvgSalary = mean(PAID_WAGE_PER_YEAR)) %>%
  

ggplot(useful_data, aes(x = WORK_STATE, y = mean(PAID_WAGE_PER_YEAR), fill = JOB_TITLE_SUBGROUP)) +
  geom_bar(stat = "identity", position = "dodge", color = "black", alpha = 0.8) +
  labs(title = "Average Salaries Across Different Locations for Job Subgroups",
       x = "Work State",
       y = "Average Salary") +
  theme_minimal()
```


```{r}
# Will the answer change if I take standard of living into account?

# I don't think standard of living affects the the wage paid per year rather the wage paid perr year may have an impact on the standards of living. Additioinally any impact the standard of liviing will have on wage will most likely be captured in the location of the job
```


